apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediclear.fullname" . }}-config
  labels:
    {{- include "mediclear.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "mediclear.redisFullname" . }}:{{ .Values.redis.port }}/0"
  {{- end }}
