"""
Structured analysis model.

The core value of MediClear over "a thin LLM wrapper" is that an analysis is a
*typed, structured object* — not an opaque markdown blob. API consumers (EHR
integrations, mobile apps) read the fields; the frontend renders from them; and
a rendered markdown convenience string is provided for quick display.

Providers return this structure directly by asking the model for JSON. If a
model returns loosely-structured text instead, :func:`StructuredAnalysis.render_markdown`
still yields something sensible from whatever fields were populated.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class DocumentType(str, Enum):
    """Detected clinical document type — drives type-specific prompting."""

    DISCHARGE_SUMMARY = "discharge_summary"
    LAB_REPORT = "lab_report"
    RADIOLOGY_REPORT = "radiology_report"
    PATHOLOGY_REPORT = "pathology_report"
    PRESCRIPTION = "prescription"
    REFERRAL_LETTER = "referral_letter"
    CONSULTATION_NOTE = "consultation_note"
    OTHER = "other"
    NOT_MEDICAL = "not_medical"


class KeyTerm(BaseModel):
    """A medical term found in the document with a plain-language definition."""

    term: str = Field(..., description="The medical term as it appears.")
    definition: str = Field(..., description="Plain-language explanation (1–2 sentences).")
    # Whether this term was actually present in the source document. Grounding
    # check: terms the model invented that are not in the source are flagged.
    found_in_source: bool = Field(
        default=True,
        description="True if the term appears in the source document (faithfulness check).",
    )
    # Provenance of the definition: the model, the bundled glossary, or an
    # online terminology source (MedlinePlus). Set by the grounding layer.
    source: Literal["model", "glossary", "online"] = Field(default="model")
    source_url: str | None = Field(
        default=None, description="Citation URL when the definition is externally sourced."
    )


class LabValue(BaseModel):
    """A structured lab result extracted from the document, when present."""

    name: str
    value: str
    unit: str | None = None
    reference_range: str | None = None
    flag: str | None = Field(default=None, description="e.g. 'high', 'low', 'normal', if stated.")


class Medication(BaseModel):
    """A medication mentioned in the document, when present."""

    name: str
    dose: str | None = None
    frequency: str | None = None
    purpose: str | None = Field(
        default=None, description="Plain-language reason, if stated in the document."
    )


class Readability(BaseModel):
    """Readability assessment of the produced explanation."""

    flesch_reading_ease: float | None = None
    estimated_cefr: str | None = Field(default=None, description="Estimated CEFR level, e.g. 'B1'.")
    target_cefr: str | None = None
    meets_target: bool | None = None


class StructuredAnalysis(BaseModel):
    """The typed result of analysing a medical document."""

    document_type: DocumentType = Field(default=DocumentType.OTHER)
    summary: str = Field(default="", description="2–3 sentence overview.")
    explanation: str = Field(default="", description="Accessible detailed explanation.")
    key_terms: list[KeyTerm] = Field(default_factory=list)
    action_items: list[str] = Field(
        default_factory=list,
        description="Practical, patient-facing takeaways and questions for the doctor.",
    )
    lab_values: list[LabValue] = Field(default_factory=list)
    medications: list[Medication] = Field(default_factory=list)
    # Populated by the service after generation, not by the model.
    readability: Readability | None = None
    disclaimer: str = Field(
        default=(
            "This explanation was generated by an AI tool for educational purposes "
            "only. It is not medical advice. Always consult a qualified healthcare "
            "professional about your care."
        )
    )

    def render_markdown(self) -> str:
        """Render a human-friendly markdown view from the structured fields."""
        if self.document_type == DocumentType.NOT_MEDICAL:
            return (
                "## This does not look like a medical document\n\n"
                f"{self.summary or self.explanation}\n"
            )

        parts: list[str] = []
        if self.summary:
            parts.append(f"## Summary\n\n{self.summary}")
        if self.explanation:
            parts.append(f"## Explanation\n\n{self.explanation}")

        if self.lab_values:
            rows = "\n".join(
                f"| {lv.name} | {lv.value}{(' ' + lv.unit) if lv.unit else ''} "
                f"| {lv.reference_range or '—'} | {lv.flag or '—'} |"
                for lv in self.lab_values
            )
            parts.append(
                "## Lab Values\n\n"
                "| Test | Result | Reference range | Flag |\n"
                "|------|--------|-----------------|------|\n"
                f"{rows}"
            )

        if self.medications:
            rows = "\n".join(
                f"- **{m.name}**"
                + (f" — {m.dose}" if m.dose else "")
                + (f", {m.frequency}" if m.frequency else "")
                + (f" ({m.purpose})" if m.purpose else "")
                for m in self.medications
            )
            parts.append(f"## Medications\n\n{rows}")

        if self.key_terms:
            rows = "\n".join(
                f"- **{kt.term}** — {kt.definition}"
                + ("" if kt.found_in_source else "  _(not found verbatim in your document)_")
                for kt in self.key_terms
            )
            parts.append(f"## Key Medical Terms\n\n{rows}")

        if self.action_items:
            rows = "\n".join(f"- {item}" for item in self.action_items)
            parts.append(f"## What This Means for You\n\n{rows}")

        parts.append(f"---\n\n_{self.disclaimer}_")
        return "\n\n".join(parts)
